version: '3'
services:
  main:
    image: hypothesis/hypothesis
    ports:
      - 5000:5000
    environment:
      APP_URL: http://localhost:5000
      AUTHORITY: localhost
      BROKER_URL: amqp://guest:guest@rabbit:5672//
      CLIENT_OAUTH_ID: 506c62a2-6b39-11ed-a730-b318819e9d30
      CLIENT_RPC_ALLOWED_ORIGINS: http://localhost:3000
      CLIENT_URL: http://localhost:3001/hypothesis
      DATABASE_URL: postgresql://postgres@postgres/postgres
      ELASTICSEARCH_URL: http://elasticsearch:9200
      NEW_RELIC_APP_NAME: "h (dev)"
      NEW_RELIC_LICENSE_KEY:
      SECRET_KEY: notasecret
      ENABLE_NGINX: true
      ENABLE_WEB: true
      ENABLE_WEBSOCKET: true
      WEBSOCKET_CONFIG: conf/websocket-monolithic.ini
      ENABLE_WORKER: true
    entrypoint: init-env supervisord -c conf/supervisord.conf
    # entrypoint: env
    depends_on:
      - postgres
      - rabbit
      - elasticsearch
  postgres:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 1s
  elasticsearch:
    image: hypothesis/elasticsearch:latest
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

